### ISSUE TITLE
Add a bracket cleaner and a splitter

### ISSUE THREAD

**Issue by LinguList** [lexibank/transnewguineaorg#1]
I just ran a test on orthography profiles, using `lingpy profile -i cldf-metadata.json -o orthography.tsv --clts --cldf --column=form --context`. This reveals a rather long list of problems, which would not occur if the form was created by using a consistent bracket remover, as well as a check for splitters, like comma, semi-colon, etc. (although they may be handled).

Profile is here:

[orthography.txt](https://github.com/lexibank/transnewguineaorg/files/2965923/orthography.txt)

A further problem is: a couple of some 5 to 10 strings (if you sort in Excel the forms) appear to be empty, but they are not captured, probably because the — is not recognized as symbol for empty strings. 

If these are captured, I think a preliminary orthography profile could be possible.

**Comment by SimonGreenhill** [comment]
Should be fixed now. `orthography.tsv` has about 2500 rows... do you think this is possible? (I can commit orthography.tsv if you want)

**Comment by LinguList** [comment]
In my experience, inspecting orthography.tsv in this way will yield more errors, so that you can systematically exclude those. could you paste orthography.tsv here in txt form?

**Comment by SimonGreenhill** [comment]
[orthography.txt](https://github.com/lexibank/transnewguineaorg/files/3010002/orthography.txt)

**Comment by LinguList** [comment]
If you search only for <?>, you'll see a few cases that are easy to fix or should be deleted. Some brackets were left unremoved, proto-forms retain the asterisk, especially diacritics with superscript meaning a weakly pronounced normal sound could be removed when building the form, already. 

One more thing, I'd recommend to test is pastying lines from the Madang profile there, as those languages had similar issues all solved by now.

But it seems doable: tedious but doable, also provided one makes some bold decisions and just simplifies some stuff.

**Comment by SimonGreenhill** [comment]
Hmm, what's best for \*reconstructions. Should the lexibank code just replace("*", "") or should we keep it and mark it as a non-token?

**Comment by LinguList** [comment]
I'd prefer to exclude all proto-languages, just as they may make problems when doing automatic analyses later. If you keep them: replace the `*` in the form and tokens makes much sense. Teh value will retain it anyway, right?

**Comment by xrotwang** [comment]
I think we should add a flag marking proto-languages in `languages.csv`. Then forms can just be cleaned like for any other language.

**Comment by SimonGreenhill** [comment]
yeah, I think we should keep the proto languages (e.g. we can use them for checking automatic reconstructions etc). For now, how about I clean them ad-hoc (```form = form.replace("*", "")```).   

Does the \* make sense as a special class in CLTS?

**Comment by LinguList** [comment]
Why not just add the asterisk to the orthoprofile? As a class in CLTS, it does not make sense, as it has no meaning other than: some people don't trust this. But if we know the language is proto, we have this for any form you write, so no need to actually use it...

**Comment by LinguList** [comment]
and by overloading your lexibank code that turns the value into the form, you could just add the `*` stripping as an additional statement, which would laos make sense, and be less ad-hoc.

**Comment by SimonGreenhill** [comment]
this should be handled now, I think.
