### ISSUE TITLE
pybtex code needs to be updated or pybtex version fixed to 0.22.2

### ISSUE THREAD

**Issue by chrzyki** [lexibank/transnewguineaorg#10]
The dataset can't be build with the most recent pybtex. Either the code that builds the bibliography needs to be updated or the version of pybtex needs to be set to `0.22.2` in `setup.py` (I assume we prefer the former?).

https://github.com/lexibank/transnewguineaorg/blob/24fe745946caa5db9bcefd2439efdeb55fd3869f/lexibank_transnewguineaorg.py#L67-L75

https://docs.pybtex.org/history.html

pybtex's `parse_string` no gives a `KeysView` that can't be indexed.

**Comment by xrotwang** [comment]
The latest pybtex release 0.23 also dropped py3.5 compat. So if we don't want to lose this, we should pin pybtex. Otherwise, yes, wrapping `list` around `parse_string` should do the trick.

**Comment by SimonGreenhill** [comment]
yeah, this is just being used to make the bibtex keys match that in the sources file so it's silly to pin to python3.5 and pybtex 0.22. Does anyone know offhand if there's a better way to do this? if not I'll take a look tomorrow or day after (have some other things to sort first)

**Comment by xrotwang** [comment]
I fixed a similar thing recently: https://github.com/lexibank/pylexibank/commit/fe9f73d9abb340e8d3e794481ae8ff67b39b5ad4#diff-8c95d47ab077d5e2667cd488669c76a395398d57ecc7443c72fc511eda015d47L172

**Comment by SimonGreenhill** [comment]
I think it's fixed here (works for me at least): https://github.com/lexibank/transnewguineaorg/pull/11

@chrzyki can you check it works for you too? danke!

**Comment by chrzyki** [comment]
Works for me. Thanks for taking care of that!

**Comment by SimonGreenhill** [comment]
fixed in #11
