### ISSUE TITLE
Many occurences of [y] seem like they might actually be [j]

### ISSUE THREAD

**Issue by XachaB** [lexibank/transnewguineaorg#14]
Hi,

From this dataset, we get many cases of [y] in intervocalic contexts in the sound correspondence study. Erich and I suspect that some of these [y] (if not all) might actually be [j]. Can someone who worked on the orthographic profile have a look at it and make the necessary changes ?

We find 2577 rows with intervocalic [y]:

```
yaqay-one-1,23022,yaqay,one,kayaqamaere,kayaqamaere,k a y a q a m a e r e,,voorhoeve-1975,,,^ k a y a q a m a e r e $,default
yawiyo-wosawari-smoke-1,196768,yawiyo-wosawari,smoke,tiyam,tiyam,t i y a m,,conrad-and-dye-1975,,,^ t i y a m $,default
siawi-snake-1,199527,siawi,snake,wiyɛmi,wiyɛmi,w i y ɛ m i,,conrad-and-dye-1975,,,^ w i y ɛ m i $,default
```

1016 rows with Vy in final:

```
kalam-stick-3,195818,kalam,stick,mon-day,mon-day,m o n + d a y,,pawley-2013,,,^ m o n - d a y $,default
kalam-to-swallow-1,195826,kalam,to-swallow,kalay-,kalay-,k a l a y,,pawley-2013,,,^ k a l a y -$,default
proto-awyu-dumut-fish-2,229008,proto-awyu-dumut,fish,*rɔxay,*rɔxay,r ɔ x a y,,healey-1970,,,^* r ɔ x a y $,default
```
and 4208 rows with yV in initial: 

```
proto-dumut-their-1,229572,proto-dumut,their,*yagi,*yagi,y a g i,,healey-1970,,,^* y a g i $,default
yawiyo-wosawari-no-not-1,196753,yawiyo-wosawari,no-not,yasʌ safiye,yasʌ_safiye,y a s ʌ + s a f i y e,,conrad-and-dye-1975,,,^ y a s ʌ _ s a f i y e $,default
worin-star-1,157000,worin,star,yɔmbɔŋ gire,yɔmbɔŋ_gire,y ɔ m b ɔ ŋ + g i r e,,mcelhanon_and_voorhoeve1970,,,^ y ɔ m b ɔ ŋ _ g i r e $,default
```

There are even more, as I ignored markers such as "+" in the search. Moreover, I can not find this grapheme at all in interconsonantic position in the forms. Comparatively, we find only 300 occurences of [j] in the entire dataset:

```
kuot-good-1,165850,kuot,good,mur,mur,m u r,adj,lindstrom2008,,,^ m u r $,default
kuot-wet-2,165893,kuot,wet,sərap,sərap,s ə r a p,adj,lindstrom2008,,,^ s ə r a p $,default
klon-halerman-seven-1,35152,klon-halerman,seven,us'uuj,us'uuj,u s uː j,,stokhof-1975,,,^ u s ' uu j $,default
kobon-empty-2,196055,kobon,empty,ij,ij,i j,+,pawley-2013,,,^ i j $,default
wambon-dog-4,214216,wambon,dog,ʔɑɴɢɑj,ʔɑɴɢɑj,ʔ ɑ ɴ ɢ ɑ j,,hughes-2009,,,^ ʔ ɑ ɴ ɢ ɑ j $,default
```

Someone who knows the languages might also want to check whether "j" in orthographic form always maps to [j] (and not, for example, [ʒ]).

The problematic rows in the orthography profile are around here:
https://github.com/lexibank/transnewguineaorg/blob/master/etc/orthography.tsv#L569

tagging @LinguList  @SimonGreenhill

**Comment by LinguList** [comment]
The profile has more problems, as you can see when looking at the lines you inspected. E.g., prenasalized consonants are de-merged as nasal plus consonatn, but only one time. @tresoldi did the profile initially. I'll check this later.

BTW: I just saw: I corrected the profile already some time ago, but did either do so in a specific branch, or did not submit it. I'll do so soon.

**Comment by LinguList** [comment]
Yes, my profile corrects for the wrong y instances (all of them).

**Comment by XachaB** [comment]
great, thanks ! I'm posting another identical issue in walkerarawakan. Maybe automatically checking for easy mistakes like y/j over all datasets would be a good idea.

**Comment by LinguList** [comment]
I found all errors in this dataset by using my check for syllables that make sense. I do not know if we not even included it already, I think even that this is the case.

BTW: for the sound correspondence code, I feel like it is time to split off a development and a test set, since you are detecting most of these problems now due to running the code for an individual problem. This can of course be criticized, so I'd suggest: splitting off a test set first, then also systematically assembling errors / improvements for data handling, getting back to individual datasets, like this one, but NOT because one found them to be strange with sound correspondences, but since we learned that intervocalic y is often in fact j, etc., what do you think, @XachaB ?

**Comment by XachaB** [comment]
I think you are right that this is how we should have processed earlier. Unfortunately, right now I don't have time to work on this a lot, or to do more advanced screening of the data, as my new project has already started. 

I am thinking of doing things as follows: (i) signal to you a few things we've seen that look like real problems (all seem fixable), (ii) re-run the current code as-is once this is corrected and write a first draft/summary of what Erich and I already have. Then, (iii) in a few months, when you think lexicore is ready and polished enough, we can re-run everything, that time using a test/dev split if necessary to further catch problems, and devote more time to it then. At that point only we should be able to make real conclusions and write the paper.

**Comment by LinguList** [comment]
Yes, this is also reasonable.

**Comment by johenglisch** [comment]
@LinguList should this be addressed before release?

**Comment by LinguList** [comment]
I handled it already! Did forget to close, sorry
