### ISSUE TITLE
Concept mapping foot/calf

### ISSUE THREAD

**Issue by chrzyki** [lexibank/transnewguineaorg#17]
- proto-trans-new-guinea-calf-1 (**kondC*) is mapped to calf but probably is calf of leg?
-  siawi-calf-1 (*gʌǏaǏi) is mapped to calf but probably is calf of leg?

Thanks for spotting this in CLICS to @AnnikaTjuka.

**Comment by johenglisch** [comment]
@LinguList should this be addressed before release?

**Comment by LinguList** [comment]
The TNG concept list is not yet integrated in the dataset, so if you correct the mapping to concepticon, this is still possible. Otherwise, I think it can also be ignored, but the issue should stay open.

**Comment by SimonGreenhill** [comment]
This should be fixed now.
