### ISSUE TITLE
Should it be "nd" or "n d" ? Inconsistency across datasets

### ISSUE THREAD

**Issue by XachaB** [lexibank/transnewguineaorg#18]
In joophonosemantic, the sequence "nd" is segmented as a single segment:

https://github.com/lexibank/joophonosemantic/blob/master/etc/orthography.tsv#L192

Example:

~~~
Enga-33_one-1,,Enga,33_one,m.e.nd.ɑ.i,m.e.nd.ɑ.i,m e nd ɑ i,,,,,^ m . e . nd . ɑ . i $,default 
~~~
However, the same sequence is segmented as "n d" in this dataset:

~~~
enga-wapi-one-1,164073,enga-wapi,one,mendai,mendai,m e n d a i,,davies_and_comrie1985,,,^ m e n d a i $,default
~~~

Is one of the two notation better, and is it possible to normalize ? This creates inconsistencies in the sound correspondence study.

See the same issue on joophonosemantic:

https://github.com/lexibank/joophonosemantic/issues/13#issuecomment-788861183

@LinguList noted there that the decision probably needs to be made also for  mb, ng, etc.

@SimonGreenhill, what do you think ?

**Comment by johenglisch** [comment]
@LinguList should this be addressed before release?

**Comment by LinguList** [comment]
@johenglisch, you could check our profile for this language and see if nd is one segment or separated, same for mb, and ng.

**Comment by LinguList** [comment]
@johenglisch, let us also ignore this issue for now, as it is far too much to assume that all nd instances are one segment in this dataset, with so many languages.

**Comment by johenglisch** [comment]
Yeah, especially since ‘pre-nasalised d’ appears to be a separate segment in the profile.

https://github.com/lexibank/transnewguineaorg/blob/2bf480419b78d3bc067d548ec3a31e2b74e4c132/etc/orthography.tsv#L932

So it wouldn't suprise me if `nd` would actually mean `n` + `d` in a few places.

**Comment by LinguList** [comment]
exactly!

**Comment by SimonGreenhill** [comment]
I think I've fixed this upstream as best I can
