### ISSUE TITLE
place concepts in etc/concepts.csv

### ISSUE THREAD

**Issue by LinguList** [lexibank/transnewguineaorg#2]
Concepticon links are currently in json, they will be easier to check if added to etc/concepts.csv

**Comment by xrotwang** [comment]
I can take care of this - ok @SimonGreenhill ?

**Comment by xrotwang** [comment]
Hm. Guess we have to decide whether we want flexibility in concepts - i.e. the tng site can add new concepts and they will show up in the lexibank dataset after `download`, or whether the list is fixed - in which case it should rather go into concepticon right away, and not just in `etc/concepts.csv`?

**Comment by LinguList** [comment]
I think it depends on the status of the concepts as a list themselves. Since TNG was conceptualized as an open-ended project, the concepticon links were then provided later on as a service, but not necessarily as something meant to be ever exhaustive. Individual subsets of the datta could be linked to concepticon, but not TNG itself, I'd say. Similarly, we would not link STEDT entirely to concepticon, right?

**Comment by xrotwang** [comment]
Ok, that's how I understood as well. But then the question is whether the tng site itself takes care of curating the concepticon links or whether that should be a service added in the lexibank dataset. If the former, we shouldn't add a full `concepts.csv` (maybe a short one to fix errata, though?), if the latter, yes, then the links should be in `concepts.csv`.

**Comment by LinguList** [comment]
You're exactly right: we could say: this is TNG's responsibility, so it does not have primarily to do with lexibank. Maybe easiest way to handle this, I was just thinking, people from our calc group (including me), might throw a quick eye on the mappings, but it's not convenient from json of course...

**Comment by SimonGreenhill** [comment]
I like the idea of tng.org maintaining the mapping itself -- that feels more natural to me? Given that it's not a standardised list, including it directly in concepticon seems odd as well.

I would love it if the CALCies could have a look at the mappings. I can easily make a table if you'd like.

**Comment by LinguList** [comment]
Okay, that would be excellent. In fact, I saw that we actually HAVE one here: https://github.com/lexibank/transnewguineaorg/blob/master/cldf/parameters.csv

So no need to have the table for visibility even, I'll ask all calcies to have a look.

**Comment by tresoldi** [comment]
I should probably be involved, remember I did the Z'graggen Madang dataset/concept list (which is part of TNG, right?): https://concepticon.clld.org/contributions/Zgraggen-1980-380

**Comment by LinguList** [comment]
I just assigned all calcies, so yes, @tresoldi, you are involved, and if you want to organize this amog the calcies, this would even be better

**Comment by LinguList** [comment]
But we can close this issue now, I'd say.

**Comment by tresoldi** [comment]
Yes, we are on it and I'll organize.

**Comment by tresoldi** [comment]
I am reopening the issue, and just pushed an initial Concepticon mapping: https://github.com/lexibank/transnewguineaorg/blob/master/etc/concepts.tsv

This mapping should help TNGorg as an organization (I agree that they should maintain an initial mapping, as this list is clearly mixing different concept lists), but it should also be enough to get started with testing lexibank integration: 909 concepts are now mapped (74%), some wrong mappings were corrected, and new items (such as those I added in the past to Concepticon related to Z'graggen's Madang and Robinson's Alor-Pantar) were linked. I also included a column with some comments of my own (especially in terms of concepts that should be added to Concepticon, from my experience with the aforementioned datasets and others for Timor languages) and collected the unique annotations for each concept when available, separating them with slashes.

The next step would be for @laiyunfan , @MacyL and @Schweikhard to review my work -- you can decide how to do it (or just split in three parts) and I can help you explain some harder concepts.

For @SimonGreenhill , which I hope has access to all sources, two questions on items I was unable to map:

- Item 69 has `barl-noun`, with the single source of Scott (1978). I have no idea what a "barl" could be, and given that this is annotated as a `(noun)` and is similar to `bark` (which not only has an edit distance of 1, but likewise a "keyboard distance" of 1 for L/K), @Schweikhard and I assumed it is probably a typo for "bark" as in "tree bark".

- Items 666 and 667 are `pubic nut` and `pubic shell`. Again, no idea what these could be, but it sounds a lot like a "testicle" and "scrotum" pair.

Could you check your sources for those two? Besides taking a look at the concept list itself, of course.

**Comment by Wu-Urbanek** [comment]
I will have a look as soon as possible :)

**Comment by LinguList** [comment]
This mapping should then be used to improve directly the mappings to Concepticon on TNG, right?

**Comment by tresoldi** [comment]
It is mostly @SimonGreenhill 's decision, but I suppose so. Still, we could use this for an initial workflow of integrating TNG data into lexibank, if so decided.

**Comment by LinguList** [comment]
I guess, this was the agreement we had in this thread: TNG provides mappings, not lexibank, so @SimonGreenhill could take the mappings in `etc/` and integrate them in TNG, and they'd be then deleted from lexibank again, right?

**Comment by tresoldi** [comment]
To be clearer: TNG should have one concept list per source, which could be used to compile raw data for lexibank (so that issues like areca- and betel-nut are fixed). These per-source concept list could very well be pre-populated from this mapping I provided, and the file itself could be trimmed down with time in order to become a common lexibank concepts.csv file.

**Comment by LinguList** [comment]
Wait, in our discussion wiht @xrotwang we decided to have NO concepts.tsv file, as we said that TNG itself provides the mapping,s so we take them from there, right? This was the main discussion in this thread. If we link individual lists in TNG to concepticon, this is another story, and then one could make separate datasets, etc., but for now, this is unrealistic, but the concept list you provide could of course help in further development. 

@SimonGreenhill, if you follow those change proposals, will it be quick to ingetrate them into TNG?

**Comment by tresoldi** [comment]
I was thinking of a local `concepts.tsv` to fix errata (as @xrotwang mentioned) or to collapse different TNG "concepts" into a single Concepticon concept, or just to select which one to map and which to skip over (like in the case of the multitude of palm trees). But doing so now is not realistic, as you say.

As for keeping the list here until TNG implements it, or move it right away to TNG, I'm fine with both. We can always revert the decision if necessary. :wink:

**Comment by SimonGreenhill** [comment]
Thanks all, working through this now. 

Re: "barl-noun" -- I've checked, this is "bark (noun)" which has now been fixed.\

Re: 666, 667 pubic nut and pubic shell, these are probably penis sheathes rather than the actual body parts themselves

Re: TNG and mappings -- yes, I'll update the mappings directly in tng.org.

Re: one dataset per source -- that is probably a discussion for another issue: see #5

**Comment by tresoldi** [comment]
So, no "barl"! It is going to be part of my list of words looking for a meaning, like [dord](https://en.wikipedia.org/wiki/Dord).

As pubic nut and shell, I've already mapped 360 `gourd-mans` to PENIS SHEATH; it might be one more case where different lists are at play (as in #5 )

**Comment by SimonGreenhill** [comment]
Thanks all, the concepts have been updated in tng.org
