### ISSUE TITLE
Wrong Glottocode for Proto-Central-Sogeram

### ISSUE THREAD

**Issue by CMUgarte** [lexibank/transnewguineaorg#23]
As raised in [lexibank/lexibank-analysed/issues/35](https://github.com/lexibank/lexibank-analysed/issues/35), there is a wrong Glottocode for Proto-Central-Sogeram. The `lexibank script` is downloading the language data directly from [http://transnewguinea.org](http://transnewguinea.org). We can probably fix this with a short `replacement table`:

| OLD Glottocode | NEW Glottocode |
| --- | --- |
| cent2257 |  |

I couldn't find the right Glottocode for the doculect (and the source link doesn't seem to work on my computer). So, if there aren't any suggestions on it, we can use this table.

Maybe, @SimonGreenhill, @xrotwang, or @tresoldi, any of you could kindly help me with this issue for the new release of Lexibank.

**Comment by SimonGreenhill** [comment]
fixed upstream. Will rebuild the dataset when I get a chance.
