### ISSUE TITLE
Wrong Language Family name

### ISSUE THREAD

**Issue by CMUgarte** [lexibank/transnewguineaorg#24]
I just spotted a wrong family name for the following languages where, instead of `Lower Sepik-Ramu`, it should be `Lower Sepik` like it's in [Glottolog](https://glottolog.org/resource/languoid/id/lowe1423). Since you solved issue #23, can I kindly ask you to fix upstream for the upcoming Lexibank release, @SimonGreenhill?

 ID | Name | Glottocode | Glottolog_Name | ISO639P3code | Macroarea | Latitude | Longitude | Family
-- | -- | -- | -- | -- | -- | -- | -- | --
 angoram | Angoram | ango1255 | Angoram | aog | Papunesia | -4.07758 | 144.028 | Lower Sepik-Ramu
  angoram-kambrindo | Angoram (Kambrindo Dialect) | ango1255 | Angoram | aog | Papunesia | -4.07758 | 144.028 | Lower Sepik-Ramu
   angoram-kanduanum | Angoram (Kanduanum Dialect) | ango1255 | Angoram | aog | Papunesia | -4.07758 | 144.028 | Lower Sepik-Ramu
   angoram-karau | Murik (Karau Dialect) | muri1260 | Murik (Papua New Guinea) | mtf | Papunesia | -3.86959 | 144.166 | Lower Sepik-Ramu
  angoram-magendo | Angoram (Magendo Dialect) | ango1255 | Angoram | aog | Papunesia | -4.07758 | 144.028 | Lower Sepik-Ramu
  angoram-marbuk | Angoram (Marbuk Dialect) | ango1255 | Angoram | aog | Papunesia | -4.07758 | 144.028 | Lower Sepik-Ramu
  angoram-wagamut | Murik (Wagamut Dialect) | muri1260 | Murik (Papua New Guinea) | mtf | Papunesia | -3.86959 | 144.166 | Lower Sepik-Ramu
  aruamu | Aruamu | arua1260 | Aruamu | msy | Papunesia | -4.28957 | 144.842 | Lower Sepik-Ramu
  awar | Awar | awar1249 | Awar | aya | Papunesia | -4.13554 | 144.836 | Lower Sepik-Ramu
  banaro | Banaro | bana1292 | Banaro | byz | Papunesia | -4.56615 | 144.329 | Lower Sepik-Ramu
  bosmun | Bosmun | bosn1248 | Bosngun | bqs | Papunesia | -4.16201 | 144.647 | Lower Sepik-Ramu
  chambri | Chambri | cham1313 | Chambri | can | Papunesia | -4.27831 | 143.097 | Lower Sepik-Ramu
  chambri-kilimbit | Chambri (Kilimbit Dialect) | cham1313 | Chambri | can | Papunesia | -4.27831 | 143.097 | Lower Sepik-Ramu
  kanggape | Kanggape | kang1291 | Kanggape | igm | Papunesia | -4.4153 | 144.816 | Lower Sepik-Ramu
  kayan | Kayan | kaia1245 | Kaian | kct | Papunesia | -4.06543 | 144.756 | Lower Sepik-Ramu
  kire | Kire | kire1240 | Kire | geb | Papunesia | -4.25927 | 144.711 | Lower Sepik-Ramu
  kopar | Kopar | kopa1248 | Kopar | xop | Papunesia | -3.98259 | 144.466 | Lower Sepik-Ramu
  kopar-singarin | Kopar (Singarin Dialect) | kopa1248 | Kopar | xop | Papunesia | -3.98259 | 144.466 | Lower Sepik-Ramu
  marangis | Marangis | wata1253 | Watam | wax | Papunesia | -4.02591 | 144.583 | Lower Sepik-Ramu
 mbore | Mbore | bore1247 | Borei | gai | Papunesia | -4.08697 | 144.715 | Lower Sepik-Ramu
  murik | Murik | muri1260 | Murik (Papua New Guinea) | mtf | Papunesia | -3.86959 | 144.166 | Lower Sepik-Ramu
  proto-lower-sepik | Proto-Lower-Sepik | lowe1437 | Lower Sepik-Ramu |   |   |   |   | Lower Sepik-Ramu
  proto-wag | Proto-Watam-Awar-Gamay | wagg1235 | Ottilien |   |   |   |   | Lower Sepik-Ramu
  rao | Rao | raoo1244 | Rao | rao | Papunesia | -4.85243 | 144.511 | Lower Sepik-Ramu
  tabriak | Tabriak | tabr1243 | Tabriak | tzx | Papunesia | -4.49162 | 143.593 | Lower Sepik-Ramu
  tanggu | Tanggu | tang1355 | Tanggu | tgu | Papunesia | -4.4621 | 144.916 | Lower Sepik-Ramu
  yimas | Yimas | yima1243 | Yimas | yee | Papunesia | -4.71731 | 143.572 | Lower Sepik-Ra

**Comment by SimonGreenhill** [comment]
Should be fixed now, thanks @MuffinLinwist
