### ISSUE TITLE
Add orthography profile

### ISSUE THREAD

**Issue by SimonGreenhill** [lexibank/transnewguineaorg#6]

**Comment by chrzyki** [comment]
Ah, just saw the issue. Ignore the release commit, sorry. :)

**Comment by xrotwang** [comment]
@SimonGreenhill this is not going to happen for CLICS 3, right?

**Comment by SimonGreenhill** [comment]
unlikely, unless @tresoldi has time?

**Comment by chrzyki** [comment]
Will release now, we can still provide the profile later, ok? :)

**Comment by tresoldi** [comment]
I've started to work on it: https://github.com/lexibank/transnewguineaorg/tree/profile

Far from finished, I'll open a PR when I need you guys involved. :smiley:
